//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_1_ADO_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeemanagementEntities : DbContext
    {
        public EmployeemanagementEntities()
            : base("name=EmployeemanagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee_Details> Employee_Details { get; set; }
    
        public virtual int AddEmployee(string empName, Nullable<decimal> empsal, string emptype)
        {
            var empNameParameter = empName != null ?
                new ObjectParameter("EmpName", empName) :
                new ObjectParameter("EmpName", typeof(string));
    
            var empsalParameter = empsal.HasValue ?
                new ObjectParameter("Empsal", empsal) :
                new ObjectParameter("Empsal", typeof(decimal));
    
            var emptypeParameter = emptype != null ?
                new ObjectParameter("Emptype", emptype) :
                new ObjectParameter("Emptype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddEmployee", empNameParameter, empsalParameter, emptypeParameter);
        }
    }
}
